In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use("fivethirtyeight")

In [ ]:
class Perceptron:
  
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"initial weights before training: \n{self.weights}")

    self.eta = eta
    self.epochs = epochs
    
  def activationFunction(self,inputs,weights):
    z= np.dot(inputs,weights)
    return np.where(z>0,1,0)

  def fit(self,X,y):
    self.X=X
    self.y=y

    X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]  # concactination
    print(f"X with bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")


      y_hat=self.activationFunction(X_with_bias,self.weights)
      print(f"predicted value : \n {y_hat}")

      self.error=self.y-y_hat
      print(f"error: \n{self.error}")

      self.weights = self.weights + self.eta*np.dot(X_with_bias.T,self.error)
      print(f"updated weights: \n{self.weights}")
      print("#############\n")

  def predict(self,X):
    X_with_bias=np.c_[X,-np.ones((len(X),1))]
    return self.activationFunction(X_with_bias,self.weights)

# AND

In [ ]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [ ]:
X = AND.drop("y", axis=1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [ ]:
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [ ]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

initial weights before training:
[6.08964854e-05 2.37969879e-04 3.37744293e-05]
X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value :
 [0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-0.4999391  -0.49976203  1.00003377]
#############

for epoch: 1
predicted value :
 [0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[6.08964854e-05 2.37969879e-04 5.00033774e-01]
#############

for epoch: 2
predicted value :
 [0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[5.00060896e-01 5.00237970e-01 3.37744293e-05]
#############

for epoch: 3
predicted value :
 [0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[6.08964854e-05 2.37969879e-04 1.00003377e+00]
#############

for epoch: 4
predicted value :
 [0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.5000609  0.50023797 0.50003377]
#############

for epoch: 5
predicted value :
 [0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[6.08964854e-05 2.37969879e-04 1.50003377e+00]
#############

for epoch: 6
predicted value :
 [0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.5000609  0.50023797 1.00003377]
#############

for epoch: 7
predicted value :
 [0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.5000609  0.50023797 1.00003377]
#############

for epoch: 8
predicted value :
 [0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.5000609  0.50023797 1.00003377]
#############

for epoch: 9
predicted value :
 [0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.5000609  0.50023797 1.00003377]
#############

In [ ]:
model.predict(X)

array([0, 0, 0, 1])

#OR

In [ ]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,1]}

OR = pd.DataFrame(data)
OR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [ ]:
X = OR.drop("y", axis=1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [ ]:
y = OR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [ ]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

initial weights before training:
[6.68903948e-05 1.40321990e-05 1.62444035e-04]
X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value :
 [0 0 0 0]
error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights:
[ 1.00006689  1.00001403 -1.49983756]
#############

for epoch: 1
predicted value :
 [1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 1.00006689  1.00001403 -0.99983756]
#############

for epoch: 2
predicted value :
 [1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 1.00006689  1.00001403 -0.49983756]
#############

for epoch: 3
predicted value :
 [1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00006689e+00 1.00001403e+00 1.62444035e-04]
#############

for epoch: 4
predicted value :
 [0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00006689e+00 1.00001403e+00 1.62444035e-04]
#############

for epoch: 5
predicted value :
 [0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00006689e+00 1.00001403e+00 1.62444035e-04]
#############

for epoch: 6
predicted value :
 [0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00006689e+00 1.00001403e+00 1.62444035e-04]
#############

for epoch: 7
predicted value :
 [0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00006689e+00 1.00001403e+00 1.62444035e-04]
#############

for epoch: 8
predicted value :
 [0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00006689e+00 1.00001403e+00 1.62444035e-04]
#############

for epoch: 9
predicted value :
 [0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00006689e+00 1.00001403e+00 1.62444035e-04]
#############