In [64]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [65]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [66]:
df.shape

(569, 33)

In [67]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [68]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [69]:
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

# Train test split

In [70]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [71]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [72]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [73]:
X_train_tensor = torch.tensor(X_train)
y_train_tensor = torch.tensor(y_train)
X_test_tensor = torch.tensor(X_test)
y_test_tensor = torch.tensor(y_test)

In [74]:
X_train

array([[-0.01330339,  1.7757658 , -0.01491962, ..., -0.13236958,
        -1.08014517, -0.03527943],
       [-0.8448276 , -0.6284278 , -0.87702746, ..., -1.11552632,
        -0.85773964, -0.72098905],
       [ 1.44755936,  0.71180168,  1.47428816, ...,  0.87583964,
         0.4967602 ,  0.46321706],
       ...,
       [-0.46608541, -1.49375484, -0.53234924, ..., -1.32388956,
        -1.02997851, -0.75145272],
       [-0.50025764, -1.62161319, -0.527814  , ..., -0.0987626 ,
         0.35796577, -0.43906159],
       [ 0.96060511,  1.21181916,  1.00427242, ...,  0.8956983 ,
        -1.23064515,  0.50697397]])

In [75]:
X_train_tensor

tensor([[-0.0133,  1.7758, -0.0149,  ..., -0.1324, -1.0801, -0.0353],
        [-0.8448, -0.6284, -0.8770,  ..., -1.1155, -0.8577, -0.7210],
        [ 1.4476,  0.7118,  1.4743,  ...,  0.8758,  0.4968,  0.4632],
        ...,
        [-0.4661, -1.4938, -0.5323,  ..., -1.3239, -1.0300, -0.7515],
        [-0.5003, -1.6216, -0.5278,  ..., -0.0988,  0.3580, -0.4391],
        [ 0.9606,  1.2118,  1.0043,  ...,  0.8957, -1.2306,  0.5070]],
       dtype=torch.float64)

In [76]:
X_train_tensor.shape

torch.Size([455, 30])

In [77]:
class MySimpleENN():

  def __init__(self,X):
    self.weights= torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    # x.shape menans how much values here..1 values every weight has random values
    self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)
    #

  def forward(self,X):
    z=torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):

    # Clamp predictions to avoid log(0)

    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
           # minimum = 0.0000001
           # maximum = 0.9999999

    # Calculate loss

    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()

    return loss

In [78]:
learning_rate = 0.1
epochs = 25

#Training Pipeline

In [79]:
model = MySimpleENN(X_train_tensor)

for epoch in range(epochs):

   # forward pass
   y_pred=model.forward(X_train_tensor)

   # loss calculate
   loss=model.loss_function(y_pred,y_train_tensor)

   # backward pass
   loss.backward()

   # parameters update
   with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

     # zero grad
    model.weights.grad.zero_()
    model.bias.grad.zero_()

   print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.9787732255118455
Epoch: 2, Loss: 2.845444095547105
Epoch: 3, Loss: 2.7117589908269824
Epoch: 4, Loss: 2.573363489354655
Epoch: 5, Loss: 2.429247468013245
Epoch: 6, Loss: 2.2868702276974493
Epoch: 7, Loss: 2.14464520693665
Epoch: 8, Loss: 2.003888270410574
Epoch: 9, Loss: 1.8702253270542533
Epoch: 10, Loss: 1.7464106004330866
Epoch: 11, Loss: 1.6332403601232843
Epoch: 12, Loss: 1.5295444012502495
Epoch: 13, Loss: 1.4309999979510533
Epoch: 14, Loss: 1.3426989881056646
Epoch: 15, Loss: 1.26389004392263
Epoch: 16, Loss: 1.1973590325098067
Epoch: 17, Loss: 1.1419740307480022
Epoch: 18, Loss: 1.0963517669525624
Epoch: 19, Loss: 1.0589708019426074
Epoch: 20, Loss: 1.0282973581842787
Epoch: 21, Loss: 1.0029015756021473
Epoch: 22, Loss: 0.981541604680789
Epoch: 23, Loss: 0.9632045849828655
Epoch: 24, Loss: 0.947107798738739
Epoch: 25, Loss: 0.9326727622923745

In [80]:
model.bias

tensor([0.5563], dtype=torch.float64, requires_grad=True)

In [81]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5867959260940552